// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

/**
 * Protobuf type {@code DersListResponse}
 */
public  final class DersListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DersListResponse)
    DersListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DersListResponse.newBuilder() to construct.
  private DersListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DersListResponse() {
    ders_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DersListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ders_ = new java.util.ArrayList<com.bilgeadam.grpc.Ders>();
              mutable_bitField0_ |= 0x00000001;
            }
            ders_.add(
                input.readMessage(com.bilgeadam.grpc.Ders.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ders_ = java.util.Collections.unmodifiableList(ders_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bilgeadam.grpc.DersListResponse.class, com.bilgeadam.grpc.DersListResponse.Builder.class);
  }

  public static final int DERS_FIELD_NUMBER = 1;
  private java.util.List<com.bilgeadam.grpc.Ders> ders_;
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  public java.util.List<com.bilgeadam.grpc.Ders> getDersList() {
    return ders_;
  }
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  public java.util.List<? extends com.bilgeadam.grpc.DersOrBuilder> 
      getDersOrBuilderList() {
    return ders_;
  }
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  public int getDersCount() {
    return ders_.size();
  }
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  public com.bilgeadam.grpc.Ders getDers(int index) {
    return ders_.get(index);
  }
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  public com.bilgeadam.grpc.DersOrBuilder getDersOrBuilder(
      int index) {
    return ders_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ders_.size(); i++) {
      output.writeMessage(1, ders_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ders_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bilgeadam.grpc.DersListResponse)) {
      return super.equals(obj);
    }
    com.bilgeadam.grpc.DersListResponse other = (com.bilgeadam.grpc.DersListResponse) obj;

    boolean result = true;
    result = result && getDersList()
        .equals(other.getDersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDersCount() > 0) {
      hash = (37 * hash) + DERS_FIELD_NUMBER;
      hash = (53 * hash) + getDersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.DersListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.DersListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bilgeadam.grpc.DersListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DersListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DersListResponse)
      com.bilgeadam.grpc.DersListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bilgeadam.grpc.DersListResponse.class, com.bilgeadam.grpc.DersListResponse.Builder.class);
    }

    // Construct using com.bilgeadam.grpc.DersListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dersBuilder_ == null) {
        ders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersListResponse_descriptor;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.DersListResponse getDefaultInstanceForType() {
      return com.bilgeadam.grpc.DersListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bilgeadam.grpc.DersListResponse build() {
      com.bilgeadam.grpc.DersListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.DersListResponse buildPartial() {
      com.bilgeadam.grpc.DersListResponse result = new com.bilgeadam.grpc.DersListResponse(this);
      int from_bitField0_ = bitField0_;
      if (dersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ders_ = java.util.Collections.unmodifiableList(ders_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ders_ = ders_;
      } else {
        result.ders_ = dersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bilgeadam.grpc.DersListResponse) {
        return mergeFrom((com.bilgeadam.grpc.DersListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bilgeadam.grpc.DersListResponse other) {
      if (other == com.bilgeadam.grpc.DersListResponse.getDefaultInstance()) return this;
      if (dersBuilder_ == null) {
        if (!other.ders_.isEmpty()) {
          if (ders_.isEmpty()) {
            ders_ = other.ders_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDersIsMutable();
            ders_.addAll(other.ders_);
          }
          onChanged();
        }
      } else {
        if (!other.ders_.isEmpty()) {
          if (dersBuilder_.isEmpty()) {
            dersBuilder_.dispose();
            dersBuilder_ = null;
            ders_ = other.ders_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDersFieldBuilder() : null;
          } else {
            dersBuilder_.addAllMessages(other.ders_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bilgeadam.grpc.DersListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bilgeadam.grpc.DersListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bilgeadam.grpc.Ders> ders_ =
      java.util.Collections.emptyList();
    private void ensureDersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ders_ = new java.util.ArrayList<com.bilgeadam.grpc.Ders>(ders_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bilgeadam.grpc.Ders, com.bilgeadam.grpc.Ders.Builder, com.bilgeadam.grpc.DersOrBuilder> dersBuilder_;

    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public java.util.List<com.bilgeadam.grpc.Ders> getDersList() {
      if (dersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ders_);
      } else {
        return dersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public int getDersCount() {
      if (dersBuilder_ == null) {
        return ders_.size();
      } else {
        return dersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.Ders getDers(int index) {
      if (dersBuilder_ == null) {
        return ders_.get(index);
      } else {
        return dersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder setDers(
        int index, com.bilgeadam.grpc.Ders value) {
      if (dersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDersIsMutable();
        ders_.set(index, value);
        onChanged();
      } else {
        dersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder setDers(
        int index, com.bilgeadam.grpc.Ders.Builder builderForValue) {
      if (dersBuilder_ == null) {
        ensureDersIsMutable();
        ders_.set(index, builderForValue.build());
        onChanged();
      } else {
        dersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder addDers(com.bilgeadam.grpc.Ders value) {
      if (dersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDersIsMutable();
        ders_.add(value);
        onChanged();
      } else {
        dersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder addDers(
        int index, com.bilgeadam.grpc.Ders value) {
      if (dersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDersIsMutable();
        ders_.add(index, value);
        onChanged();
      } else {
        dersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder addDers(
        com.bilgeadam.grpc.Ders.Builder builderForValue) {
      if (dersBuilder_ == null) {
        ensureDersIsMutable();
        ders_.add(builderForValue.build());
        onChanged();
      } else {
        dersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder addDers(
        int index, com.bilgeadam.grpc.Ders.Builder builderForValue) {
      if (dersBuilder_ == null) {
        ensureDersIsMutable();
        ders_.add(index, builderForValue.build());
        onChanged();
      } else {
        dersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder addAllDers(
        java.lang.Iterable<? extends com.bilgeadam.grpc.Ders> values) {
      if (dersBuilder_ == null) {
        ensureDersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ders_);
        onChanged();
      } else {
        dersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder clearDers() {
      if (dersBuilder_ == null) {
        ders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public Builder removeDers(int index) {
      if (dersBuilder_ == null) {
        ensureDersIsMutable();
        ders_.remove(index);
        onChanged();
      } else {
        dersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.Ders.Builder getDersBuilder(
        int index) {
      return getDersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.DersOrBuilder getDersOrBuilder(
        int index) {
      if (dersBuilder_ == null) {
        return ders_.get(index);  } else {
        return dersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public java.util.List<? extends com.bilgeadam.grpc.DersOrBuilder> 
         getDersOrBuilderList() {
      if (dersBuilder_ != null) {
        return dersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ders_);
      }
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.Ders.Builder addDersBuilder() {
      return getDersFieldBuilder().addBuilder(
          com.bilgeadam.grpc.Ders.getDefaultInstance());
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.Ders.Builder addDersBuilder(
        int index) {
      return getDersFieldBuilder().addBuilder(
          index, com.bilgeadam.grpc.Ders.getDefaultInstance());
    }
    /**
     * <code>repeated .Ders ders = 1;</code>
     */
    public java.util.List<com.bilgeadam.grpc.Ders.Builder> 
         getDersBuilderList() {
      return getDersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bilgeadam.grpc.Ders, com.bilgeadam.grpc.Ders.Builder, com.bilgeadam.grpc.DersOrBuilder> 
        getDersFieldBuilder() {
      if (dersBuilder_ == null) {
        dersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bilgeadam.grpc.Ders, com.bilgeadam.grpc.Ders.Builder, com.bilgeadam.grpc.DersOrBuilder>(
                ders_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        ders_ = null;
      }
      return dersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DersListResponse)
  }

  // @@protoc_insertion_point(class_scope:DersListResponse)
  private static final com.bilgeadam.grpc.DersListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bilgeadam.grpc.DersListResponse();
  }

  public static com.bilgeadam.grpc.DersListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DersListResponse>
      PARSER = new com.google.protobuf.AbstractParser<DersListResponse>() {
    @java.lang.Override
    public DersListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DersListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DersListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DersListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bilgeadam.grpc.DersListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

