// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

/**
 * Protobuf type {@code DersInsertRequest}
 */
public  final class DersInsertRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DersInsertRequest)
    DersInsertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DersInsertRequest.newBuilder() to construct.
  private DersInsertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DersInsertRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DersInsertRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.bilgeadam.grpc.Ders.Builder subBuilder = null;
            if (ders_ != null) {
              subBuilder = ders_.toBuilder();
            }
            ders_ = input.readMessage(com.bilgeadam.grpc.Ders.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ders_);
              ders_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersInsertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersInsertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bilgeadam.grpc.DersInsertRequest.class, com.bilgeadam.grpc.DersInsertRequest.Builder.class);
  }

  public static final int DERS_FIELD_NUMBER = 1;
  private com.bilgeadam.grpc.Ders ders_;
  /**
   * <code>.Ders ders = 1;</code>
   */
  public boolean hasDers() {
    return ders_ != null;
  }
  /**
   * <code>.Ders ders = 1;</code>
   */
  public com.bilgeadam.grpc.Ders getDers() {
    return ders_ == null ? com.bilgeadam.grpc.Ders.getDefaultInstance() : ders_;
  }
  /**
   * <code>.Ders ders = 1;</code>
   */
  public com.bilgeadam.grpc.DersOrBuilder getDersOrBuilder() {
    return getDers();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ders_ != null) {
      output.writeMessage(1, getDers());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ders_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDers());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bilgeadam.grpc.DersInsertRequest)) {
      return super.equals(obj);
    }
    com.bilgeadam.grpc.DersInsertRequest other = (com.bilgeadam.grpc.DersInsertRequest) obj;

    boolean result = true;
    result = result && (hasDers() == other.hasDers());
    if (hasDers()) {
      result = result && getDers()
          .equals(other.getDers());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDers()) {
      hash = (37 * hash) + DERS_FIELD_NUMBER;
      hash = (53 * hash) + getDers().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.DersInsertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bilgeadam.grpc.DersInsertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DersInsertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DersInsertRequest)
      com.bilgeadam.grpc.DersInsertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersInsertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersInsertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bilgeadam.grpc.DersInsertRequest.class, com.bilgeadam.grpc.DersInsertRequest.Builder.class);
    }

    // Construct using com.bilgeadam.grpc.DersInsertRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dersBuilder_ == null) {
        ders_ = null;
      } else {
        ders_ = null;
        dersBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_DersInsertRequest_descriptor;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.DersInsertRequest getDefaultInstanceForType() {
      return com.bilgeadam.grpc.DersInsertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.bilgeadam.grpc.DersInsertRequest build() {
      com.bilgeadam.grpc.DersInsertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.DersInsertRequest buildPartial() {
      com.bilgeadam.grpc.DersInsertRequest result = new com.bilgeadam.grpc.DersInsertRequest(this);
      if (dersBuilder_ == null) {
        result.ders_ = ders_;
      } else {
        result.ders_ = dersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bilgeadam.grpc.DersInsertRequest) {
        return mergeFrom((com.bilgeadam.grpc.DersInsertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bilgeadam.grpc.DersInsertRequest other) {
      if (other == com.bilgeadam.grpc.DersInsertRequest.getDefaultInstance()) return this;
      if (other.hasDers()) {
        mergeDers(other.getDers());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bilgeadam.grpc.DersInsertRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bilgeadam.grpc.DersInsertRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.bilgeadam.grpc.Ders ders_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bilgeadam.grpc.Ders, com.bilgeadam.grpc.Ders.Builder, com.bilgeadam.grpc.DersOrBuilder> dersBuilder_;
    /**
     * <code>.Ders ders = 1;</code>
     */
    public boolean hasDers() {
      return dersBuilder_ != null || ders_ != null;
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.Ders getDers() {
      if (dersBuilder_ == null) {
        return ders_ == null ? com.bilgeadam.grpc.Ders.getDefaultInstance() : ders_;
      } else {
        return dersBuilder_.getMessage();
      }
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public Builder setDers(com.bilgeadam.grpc.Ders value) {
      if (dersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ders_ = value;
        onChanged();
      } else {
        dersBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public Builder setDers(
        com.bilgeadam.grpc.Ders.Builder builderForValue) {
      if (dersBuilder_ == null) {
        ders_ = builderForValue.build();
        onChanged();
      } else {
        dersBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public Builder mergeDers(com.bilgeadam.grpc.Ders value) {
      if (dersBuilder_ == null) {
        if (ders_ != null) {
          ders_ =
            com.bilgeadam.grpc.Ders.newBuilder(ders_).mergeFrom(value).buildPartial();
        } else {
          ders_ = value;
        }
        onChanged();
      } else {
        dersBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public Builder clearDers() {
      if (dersBuilder_ == null) {
        ders_ = null;
        onChanged();
      } else {
        ders_ = null;
        dersBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.Ders.Builder getDersBuilder() {
      
      onChanged();
      return getDersFieldBuilder().getBuilder();
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    public com.bilgeadam.grpc.DersOrBuilder getDersOrBuilder() {
      if (dersBuilder_ != null) {
        return dersBuilder_.getMessageOrBuilder();
      } else {
        return ders_ == null ?
            com.bilgeadam.grpc.Ders.getDefaultInstance() : ders_;
      }
    }
    /**
     * <code>.Ders ders = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bilgeadam.grpc.Ders, com.bilgeadam.grpc.Ders.Builder, com.bilgeadam.grpc.DersOrBuilder> 
        getDersFieldBuilder() {
      if (dersBuilder_ == null) {
        dersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bilgeadam.grpc.Ders, com.bilgeadam.grpc.Ders.Builder, com.bilgeadam.grpc.DersOrBuilder>(
                getDers(),
                getParentForChildren(),
                isClean());
        ders_ = null;
      }
      return dersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DersInsertRequest)
  }

  // @@protoc_insertion_point(class_scope:DersInsertRequest)
  private static final com.bilgeadam.grpc.DersInsertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bilgeadam.grpc.DersInsertRequest();
  }

  public static com.bilgeadam.grpc.DersInsertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DersInsertRequest>
      PARSER = new com.google.protobuf.AbstractParser<DersInsertRequest>() {
    @java.lang.Override
    public DersInsertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DersInsertRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DersInsertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DersInsertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bilgeadam.grpc.DersInsertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

