// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface DersInsertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DersInsertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Ders ders = 1;</code>
   */
  boolean hasDers();
  /**
   * <code>.Ders ders = 1;</code>
   */
  com.bilgeadam.grpc.Ders getDers();
  /**
   * <code>.Ders ders = 1;</code>
   */
  com.bilgeadam.grpc.DersOrBuilder getDersOrBuilder();
}
