// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface DersListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DersListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  java.util.List<com.bilgeadam.grpc.Ders> 
      getDersList();
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  com.bilgeadam.grpc.Ders getDers(int index);
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  int getDersCount();
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  java.util.List<? extends com.bilgeadam.grpc.DersOrBuilder> 
      getDersOrBuilderList();
  /**
   * <code>repeated .Ders ders = 1;</code>
   */
  com.bilgeadam.grpc.DersOrBuilder getDersOrBuilder(
      int index);
}
