// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface DersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string ders_name = 2;</code>
   */
  java.lang.String getDersName();
  /**
   * <code>string ders_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getDersNameBytes();

  /**
   * <code>int64 ogr_id = 3;</code>
   */
  long getOgrId();
}
