// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public final class OgrenciDersOuterClass {
  private OgrenciDersOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ogrenci_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ogrenci_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciGetByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciGetByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciGetByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciGetByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDersUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDersUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDersUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDersUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDersUpdateAddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDersUpdateAddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDersUpdateAddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDersUpdateAddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciInsertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciInsertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciInsertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciInsertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ders_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ders_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DersListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DersListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DersListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DersListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DersDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DersDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DersDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DersDeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DersInsertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DersInsertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DersInsertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DersInsertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDersListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDersListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OgrenciDersListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OgrenciDersListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021OgrenciDers.proto\"r\n\007Ogrenci\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\022\022\n\nogr_number\030\003 \001(\003\022\014\n\004" +
      "year\030\004 \001(\003\022\r\n\005ders1\030\005 \001(\t\022\r\n\005ders2\030\006 \001(\t" +
      "\022\r\n\005ders3\030\007 \001(\t\"#\n\025OgrenciGetByIdRequest" +
      "\022\n\n\002id\030\001 \001(\005\"3\n\026OgrenciGetByIdResponse\022\031" +
      "\n\007ogrenci\030\001 \001(\0132\010.Ogrenci\"\024\n\022OgrenciList" +
      "Request\"0\n\023OgrenciListResponse\022\031\n\007ogrenc" +
      "i\030\001 \003(\0132\010.Ogrenci\"\"\n\024OgrenciDeleteReques" +
      "t\022\n\n\002id\030\001 \001(\005\")\n\025OgrenciDeleteResponse\022\020" +
      "\n\010isDelete\030\001 \001(\010\"&\n\030OgrenciDersUpdateReq" +
      "uest\022\n\n\002id\030\001 \001(\005\"-\n\031OgrenciDersUpdateRes" +
      "ponse\022\020\n\010isDelete\030\001 \001(\010\"D\n\033OgrenciDersUp" +
      "dateAddRequest\022\031\n\007ogrenci\030\001 \001(\0132\010.Ogrenc" +
      "i\022\n\n\002id\030\002 \001(\005\"0\n\034OgrenciDersUpdateAddRes" +
      "ponse\022\020\n\010isDelete\030\001 \001(\010\"1\n\024OgrenciInsert" +
      "Request\022\031\n\007ogrenci\030\001 \001(\0132\010.Ogrenci\"(\n\025Og" +
      "renciInsertResponse\022\017\n\007isSaved\030\001 \001(\010\"=\n\024" +
      "OgrenciUpdateRequest\022\031\n\007ogrenci\030\001 \001(\0132\010." +
      "Ogrenci\022\n\n\002id\030\002 \001(\005\"*\n\025OgrenciUpdateResp" +
      "onse\022\021\n\tisUpdated\030\001 \001(\010\"5\n\004Ders\022\n\n\002id\030\001 " +
      "\001(\003\022\021\n\tders_name\030\002 \001(\t\022\016\n\006ogr_id\030\003 \001(\003\"\021" +
      "\n\017DersListRequest\"\'\n\020DersListResponse\022\023\n" +
      "\004ders\030\001 \003(\0132\005.Ders\"\037\n\021DersDeleteRequest\022" +
      "\n\n\002id\030\001 \001(\005\"&\n\022DersDeleteResponse\022\020\n\010isD" +
      "elete\030\001 \001(\010\"(\n\021DersInsertRequest\022\023\n\004ders" +
      "\030\001 \001(\0132\005.Ders\"%\n\022DersInsertResponse\022\017\n\007i" +
      "sSaved\030\001 \001(\010\"l\n\013OgrenciDers\022\n\n\002id\030\001 \001(\003\022" +
      "\014\n\004name\030\002 \001(\t\022\022\n\nogr_number\030\003 \001(\003\022\014\n\004yea" +
      "r\030\004 \001(\003\022\021\n\tders_name\030\005 \001(\t\022\016\n\006ogr_id\030\006 \001" +
      "(\003\"\030\n\026OgrenciDersListRequest\"<\n\027OgrenciD" +
      "ersListResponse\022!\n\013ogrenciDers\030\001 \003(\0132\014.O" +
      "grenciDers2\341\005\n\020OperationService\022=\n\nSetOg" +
      "renci\022\025.OgrenciInsertRequest\032\026.OgrenciIn" +
      "sertResponse\"\000\022@\n\rUpdateOgrenci\022\025.Ogrenc" +
      "iUpdateRequest\032\026.OgrenciUpdateResponse\"\000" +
      "\022R\n\021UpdateOgrenciDers\022\034.OgrenciDersUpdat" +
      "eAddRequest\032\035.OgrenciDersUpdateAddRespon" +
      "se\"\000\022K\n\020EmptyOgrenciDers\022\031.OgrenciDersUp" +
      "dateRequest\032\032.OgrenciDersUpdateResponse\"" +
      "\000\022@\n\rDeleteOgrenci\022\025.OgrenciDeleteReques" +
      "t\032\026.OgrenciDeleteResponse\"\000\022:\n\013ListOgren" +
      "ci\022\023.OgrenciListRequest\032\024.OgrenciListRes" +
      "ponse\"\000\022C\n\016OgrenciGetById\022\026.OgrenciGetBy" +
      "IdRequest\032\027.OgrenciGetByIdResponse\"\000\0224\n\007" +
      "SetDers\022\022.DersInsertRequest\032\023.DersInsert" +
      "Response\"\000\0227\n\nDeleteDers\022\022.DersDeleteReq" +
      "uest\032\023.DersDeleteResponse\"\000\0221\n\010ListDers\022" +
      "\020.DersListRequest\032\021.DersListResponse\"\000\022F" +
      "\n\017ListOgrenciDers\022\027.OgrenciDersListReque" +
      "st\032\030.OgrenciDersListResponse\"\000B\026\n\022com.bi" +
      "lgeadam.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Ogrenci_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ogrenci_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ogrenci_descriptor,
        new java.lang.String[] { "Id", "Name", "OgrNumber", "Year", "Ders1", "Ders2", "Ders3", });
    internal_static_OgrenciGetByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OgrenciGetByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciGetByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_OgrenciGetByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OgrenciGetByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciGetByIdResponse_descriptor,
        new java.lang.String[] { "Ogrenci", });
    internal_static_OgrenciListRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_OgrenciListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_OgrenciListResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OgrenciListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciListResponse_descriptor,
        new java.lang.String[] { "Ogrenci", });
    internal_static_OgrenciDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OgrenciDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_OgrenciDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_OgrenciDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDeleteResponse_descriptor,
        new java.lang.String[] { "IsDelete", });
    internal_static_OgrenciDersUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_OgrenciDersUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDersUpdateRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_OgrenciDersUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_OgrenciDersUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDersUpdateResponse_descriptor,
        new java.lang.String[] { "IsDelete", });
    internal_static_OgrenciDersUpdateAddRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_OgrenciDersUpdateAddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDersUpdateAddRequest_descriptor,
        new java.lang.String[] { "Ogrenci", "Id", });
    internal_static_OgrenciDersUpdateAddResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_OgrenciDersUpdateAddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDersUpdateAddResponse_descriptor,
        new java.lang.String[] { "IsDelete", });
    internal_static_OgrenciInsertRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_OgrenciInsertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciInsertRequest_descriptor,
        new java.lang.String[] { "Ogrenci", });
    internal_static_OgrenciInsertResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_OgrenciInsertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciInsertResponse_descriptor,
        new java.lang.String[] { "IsSaved", });
    internal_static_OgrenciUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_OgrenciUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciUpdateRequest_descriptor,
        new java.lang.String[] { "Ogrenci", "Id", });
    internal_static_OgrenciUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_OgrenciUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciUpdateResponse_descriptor,
        new java.lang.String[] { "IsUpdated", });
    internal_static_Ders_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Ders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ders_descriptor,
        new java.lang.String[] { "Id", "DersName", "OgrId", });
    internal_static_DersListRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_DersListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DersListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_DersListResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_DersListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DersListResponse_descriptor,
        new java.lang.String[] { "Ders", });
    internal_static_DersDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_DersDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DersDeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DersDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_DersDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DersDeleteResponse_descriptor,
        new java.lang.String[] { "IsDelete", });
    internal_static_DersInsertRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_DersInsertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DersInsertRequest_descriptor,
        new java.lang.String[] { "Ders", });
    internal_static_DersInsertResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_DersInsertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DersInsertResponse_descriptor,
        new java.lang.String[] { "IsSaved", });
    internal_static_OgrenciDers_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_OgrenciDers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDers_descriptor,
        new java.lang.String[] { "Id", "Name", "OgrNumber", "Year", "DersName", "OgrId", });
    internal_static_OgrenciDersListRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_OgrenciDersListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDersListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_OgrenciDersListResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_OgrenciDersListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OgrenciDersListResponse_descriptor,
        new java.lang.String[] { "OgrenciDers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
