// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ogrenci)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 ogr_number = 3;</code>
   */
  long getOgrNumber();

  /**
   * <code>int64 year = 4;</code>
   */
  long getYear();

  /**
   * <code>string ders1 = 5;</code>
   */
  java.lang.String getDers1();
  /**
   * <code>string ders1 = 5;</code>
   */
  com.google.protobuf.ByteString
      getDers1Bytes();

  /**
   * <code>string ders2 = 6;</code>
   */
  java.lang.String getDers2();
  /**
   * <code>string ders2 = 6;</code>
   */
  com.google.protobuf.ByteString
      getDers2Bytes();

  /**
   * <code>string ders3 = 7;</code>
   */
  java.lang.String getDers3();
  /**
   * <code>string ders3 = 7;</code>
   */
  com.google.protobuf.ByteString
      getDers3Bytes();
}
