// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciInsertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciInsertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSaved = 1;</code>
   */
  boolean getIsSaved();
}
