// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciDersUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciDersUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isDelete = 1;</code>
   */
  boolean getIsDelete();
}
