// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciDersListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciDersListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  java.util.List<com.bilgeadam.grpc.OgrenciDers> 
      getOgrenciDersList();
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  com.bilgeadam.grpc.OgrenciDers getOgrenciDers(int index);
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  int getOgrenciDersCount();
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  java.util.List<? extends com.bilgeadam.grpc.OgrenciDersOrBuilder> 
      getOgrenciDersOrBuilderList();
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  com.bilgeadam.grpc.OgrenciDersOrBuilder getOgrenciDersOrBuilder(
      int index);
}
