// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciListRequest)
    com.google.protobuf.MessageOrBuilder {
}
