// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciDersUpdateAddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciDersUpdateAddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Ogrenci ogrenci = 1;</code>
   */
  boolean hasOgrenci();
  /**
   * <code>.Ogrenci ogrenci = 1;</code>
   */
  com.bilgeadam.grpc.Ogrenci getOgrenci();
  /**
   * <code>.Ogrenci ogrenci = 1;</code>
   */
  com.bilgeadam.grpc.OgrenciOrBuilder getOgrenciOrBuilder();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
