// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciDersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciDers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 ogr_number = 3;</code>
   */
  long getOgrNumber();

  /**
   * <code>int64 year = 4;</code>
   */
  long getYear();

  /**
   * <code>string ders_name = 5;</code>
   */
  java.lang.String getDersName();
  /**
   * <code>string ders_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getDersNameBytes();

  /**
   * <code>int64 ogr_id = 6;</code>
   */
  long getOgrId();
}
