// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciDersListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciDersListRequest)
    com.google.protobuf.MessageOrBuilder {
}
