// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

/**
 * Protobuf type {@code OgrenciDersListResponse}
 */
public  final class OgrenciDersListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OgrenciDersListResponse)
    OgrenciDersListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OgrenciDersListResponse.newBuilder() to construct.
  private OgrenciDersListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OgrenciDersListResponse() {
    ogrenciDers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OgrenciDersListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ogrenciDers_ = new java.util.ArrayList<com.bilgeadam.grpc.OgrenciDers>();
              mutable_bitField0_ |= 0x00000001;
            }
            ogrenciDers_.add(
                input.readMessage(com.bilgeadam.grpc.OgrenciDers.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ogrenciDers_ = java.util.Collections.unmodifiableList(ogrenciDers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDersListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDersListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bilgeadam.grpc.OgrenciDersListResponse.class, com.bilgeadam.grpc.OgrenciDersListResponse.Builder.class);
  }

  public static final int OGRENCIDERS_FIELD_NUMBER = 1;
  private java.util.List<com.bilgeadam.grpc.OgrenciDers> ogrenciDers_;
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  public java.util.List<com.bilgeadam.grpc.OgrenciDers> getOgrenciDersList() {
    return ogrenciDers_;
  }
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  public java.util.List<? extends com.bilgeadam.grpc.OgrenciDersOrBuilder> 
      getOgrenciDersOrBuilderList() {
    return ogrenciDers_;
  }
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  public int getOgrenciDersCount() {
    return ogrenciDers_.size();
  }
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  public com.bilgeadam.grpc.OgrenciDers getOgrenciDers(int index) {
    return ogrenciDers_.get(index);
  }
  /**
   * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
   */
  public com.bilgeadam.grpc.OgrenciDersOrBuilder getOgrenciDersOrBuilder(
      int index) {
    return ogrenciDers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ogrenciDers_.size(); i++) {
      output.writeMessage(1, ogrenciDers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ogrenciDers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ogrenciDers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bilgeadam.grpc.OgrenciDersListResponse)) {
      return super.equals(obj);
    }
    com.bilgeadam.grpc.OgrenciDersListResponse other = (com.bilgeadam.grpc.OgrenciDersListResponse) obj;

    boolean result = true;
    result = result && getOgrenciDersList()
        .equals(other.getOgrenciDersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOgrenciDersCount() > 0) {
      hash = (37 * hash) + OGRENCIDERS_FIELD_NUMBER;
      hash = (53 * hash) + getOgrenciDersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.OgrenciDersListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bilgeadam.grpc.OgrenciDersListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OgrenciDersListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OgrenciDersListResponse)
      com.bilgeadam.grpc.OgrenciDersListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDersListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDersListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bilgeadam.grpc.OgrenciDersListResponse.class, com.bilgeadam.grpc.OgrenciDersListResponse.Builder.class);
    }

    // Construct using com.bilgeadam.grpc.OgrenciDersListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOgrenciDersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ogrenciDersBuilder_ == null) {
        ogrenciDers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ogrenciDersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDersListResponse_descriptor;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.OgrenciDersListResponse getDefaultInstanceForType() {
      return com.bilgeadam.grpc.OgrenciDersListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bilgeadam.grpc.OgrenciDersListResponse build() {
      com.bilgeadam.grpc.OgrenciDersListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.OgrenciDersListResponse buildPartial() {
      com.bilgeadam.grpc.OgrenciDersListResponse result = new com.bilgeadam.grpc.OgrenciDersListResponse(this);
      int from_bitField0_ = bitField0_;
      if (ogrenciDersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ogrenciDers_ = java.util.Collections.unmodifiableList(ogrenciDers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ogrenciDers_ = ogrenciDers_;
      } else {
        result.ogrenciDers_ = ogrenciDersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bilgeadam.grpc.OgrenciDersListResponse) {
        return mergeFrom((com.bilgeadam.grpc.OgrenciDersListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bilgeadam.grpc.OgrenciDersListResponse other) {
      if (other == com.bilgeadam.grpc.OgrenciDersListResponse.getDefaultInstance()) return this;
      if (ogrenciDersBuilder_ == null) {
        if (!other.ogrenciDers_.isEmpty()) {
          if (ogrenciDers_.isEmpty()) {
            ogrenciDers_ = other.ogrenciDers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOgrenciDersIsMutable();
            ogrenciDers_.addAll(other.ogrenciDers_);
          }
          onChanged();
        }
      } else {
        if (!other.ogrenciDers_.isEmpty()) {
          if (ogrenciDersBuilder_.isEmpty()) {
            ogrenciDersBuilder_.dispose();
            ogrenciDersBuilder_ = null;
            ogrenciDers_ = other.ogrenciDers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ogrenciDersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOgrenciDersFieldBuilder() : null;
          } else {
            ogrenciDersBuilder_.addAllMessages(other.ogrenciDers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bilgeadam.grpc.OgrenciDersListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bilgeadam.grpc.OgrenciDersListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bilgeadam.grpc.OgrenciDers> ogrenciDers_ =
      java.util.Collections.emptyList();
    private void ensureOgrenciDersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ogrenciDers_ = new java.util.ArrayList<com.bilgeadam.grpc.OgrenciDers>(ogrenciDers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bilgeadam.grpc.OgrenciDers, com.bilgeadam.grpc.OgrenciDers.Builder, com.bilgeadam.grpc.OgrenciDersOrBuilder> ogrenciDersBuilder_;

    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public java.util.List<com.bilgeadam.grpc.OgrenciDers> getOgrenciDersList() {
      if (ogrenciDersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ogrenciDers_);
      } else {
        return ogrenciDersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public int getOgrenciDersCount() {
      if (ogrenciDersBuilder_ == null) {
        return ogrenciDers_.size();
      } else {
        return ogrenciDersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public com.bilgeadam.grpc.OgrenciDers getOgrenciDers(int index) {
      if (ogrenciDersBuilder_ == null) {
        return ogrenciDers_.get(index);
      } else {
        return ogrenciDersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder setOgrenciDers(
        int index, com.bilgeadam.grpc.OgrenciDers value) {
      if (ogrenciDersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOgrenciDersIsMutable();
        ogrenciDers_.set(index, value);
        onChanged();
      } else {
        ogrenciDersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder setOgrenciDers(
        int index, com.bilgeadam.grpc.OgrenciDers.Builder builderForValue) {
      if (ogrenciDersBuilder_ == null) {
        ensureOgrenciDersIsMutable();
        ogrenciDers_.set(index, builderForValue.build());
        onChanged();
      } else {
        ogrenciDersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder addOgrenciDers(com.bilgeadam.grpc.OgrenciDers value) {
      if (ogrenciDersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOgrenciDersIsMutable();
        ogrenciDers_.add(value);
        onChanged();
      } else {
        ogrenciDersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder addOgrenciDers(
        int index, com.bilgeadam.grpc.OgrenciDers value) {
      if (ogrenciDersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOgrenciDersIsMutable();
        ogrenciDers_.add(index, value);
        onChanged();
      } else {
        ogrenciDersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder addOgrenciDers(
        com.bilgeadam.grpc.OgrenciDers.Builder builderForValue) {
      if (ogrenciDersBuilder_ == null) {
        ensureOgrenciDersIsMutable();
        ogrenciDers_.add(builderForValue.build());
        onChanged();
      } else {
        ogrenciDersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder addOgrenciDers(
        int index, com.bilgeadam.grpc.OgrenciDers.Builder builderForValue) {
      if (ogrenciDersBuilder_ == null) {
        ensureOgrenciDersIsMutable();
        ogrenciDers_.add(index, builderForValue.build());
        onChanged();
      } else {
        ogrenciDersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder addAllOgrenciDers(
        java.lang.Iterable<? extends com.bilgeadam.grpc.OgrenciDers> values) {
      if (ogrenciDersBuilder_ == null) {
        ensureOgrenciDersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ogrenciDers_);
        onChanged();
      } else {
        ogrenciDersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder clearOgrenciDers() {
      if (ogrenciDersBuilder_ == null) {
        ogrenciDers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ogrenciDersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public Builder removeOgrenciDers(int index) {
      if (ogrenciDersBuilder_ == null) {
        ensureOgrenciDersIsMutable();
        ogrenciDers_.remove(index);
        onChanged();
      } else {
        ogrenciDersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public com.bilgeadam.grpc.OgrenciDers.Builder getOgrenciDersBuilder(
        int index) {
      return getOgrenciDersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public com.bilgeadam.grpc.OgrenciDersOrBuilder getOgrenciDersOrBuilder(
        int index) {
      if (ogrenciDersBuilder_ == null) {
        return ogrenciDers_.get(index);  } else {
        return ogrenciDersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public java.util.List<? extends com.bilgeadam.grpc.OgrenciDersOrBuilder> 
         getOgrenciDersOrBuilderList() {
      if (ogrenciDersBuilder_ != null) {
        return ogrenciDersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ogrenciDers_);
      }
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public com.bilgeadam.grpc.OgrenciDers.Builder addOgrenciDersBuilder() {
      return getOgrenciDersFieldBuilder().addBuilder(
          com.bilgeadam.grpc.OgrenciDers.getDefaultInstance());
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public com.bilgeadam.grpc.OgrenciDers.Builder addOgrenciDersBuilder(
        int index) {
      return getOgrenciDersFieldBuilder().addBuilder(
          index, com.bilgeadam.grpc.OgrenciDers.getDefaultInstance());
    }
    /**
     * <code>repeated .OgrenciDers ogrenciDers = 1;</code>
     */
    public java.util.List<com.bilgeadam.grpc.OgrenciDers.Builder> 
         getOgrenciDersBuilderList() {
      return getOgrenciDersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bilgeadam.grpc.OgrenciDers, com.bilgeadam.grpc.OgrenciDers.Builder, com.bilgeadam.grpc.OgrenciDersOrBuilder> 
        getOgrenciDersFieldBuilder() {
      if (ogrenciDersBuilder_ == null) {
        ogrenciDersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bilgeadam.grpc.OgrenciDers, com.bilgeadam.grpc.OgrenciDers.Builder, com.bilgeadam.grpc.OgrenciDersOrBuilder>(
                ogrenciDers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        ogrenciDers_ = null;
      }
      return ogrenciDersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OgrenciDersListResponse)
  }

  // @@protoc_insertion_point(class_scope:OgrenciDersListResponse)
  private static final com.bilgeadam.grpc.OgrenciDersListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bilgeadam.grpc.OgrenciDersListResponse();
  }

  public static com.bilgeadam.grpc.OgrenciDersListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OgrenciDersListResponse>
      PARSER = new com.google.protobuf.AbstractParser<OgrenciDersListResponse>() {
    @java.lang.Override
    public OgrenciDersListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OgrenciDersListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OgrenciDersListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OgrenciDersListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bilgeadam.grpc.OgrenciDersListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

