// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

/**
 * Protobuf type {@code OgrenciDers}
 */
public  final class OgrenciDers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OgrenciDers)
    OgrenciDersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OgrenciDers.newBuilder() to construct.
  private OgrenciDers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OgrenciDers() {
    id_ = 0L;
    name_ = "";
    ogrNumber_ = 0L;
    year_ = 0L;
    dersName_ = "";
    ogrId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OgrenciDers(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            ogrNumber_ = input.readInt64();
            break;
          }
          case 32: {

            year_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dersName_ = s;
            break;
          }
          case 48: {

            ogrId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bilgeadam.grpc.OgrenciDers.class, com.bilgeadam.grpc.OgrenciDers.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OGR_NUMBER_FIELD_NUMBER = 3;
  private long ogrNumber_;
  /**
   * <code>int64 ogr_number = 3;</code>
   */
  public long getOgrNumber() {
    return ogrNumber_;
  }

  public static final int YEAR_FIELD_NUMBER = 4;
  private long year_;
  /**
   * <code>int64 year = 4;</code>
   */
  public long getYear() {
    return year_;
  }

  public static final int DERS_NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object dersName_;
  /**
   * <code>string ders_name = 5;</code>
   */
  public java.lang.String getDersName() {
    java.lang.Object ref = dersName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dersName_ = s;
      return s;
    }
  }
  /**
   * <code>string ders_name = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDersNameBytes() {
    java.lang.Object ref = dersName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dersName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OGR_ID_FIELD_NUMBER = 6;
  private long ogrId_;
  /**
   * <code>int64 ogr_id = 6;</code>
   */
  public long getOgrId() {
    return ogrId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (ogrNumber_ != 0L) {
      output.writeInt64(3, ogrNumber_);
    }
    if (year_ != 0L) {
      output.writeInt64(4, year_);
    }
    if (!getDersNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dersName_);
    }
    if (ogrId_ != 0L) {
      output.writeInt64(6, ogrId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (ogrNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, ogrNumber_);
    }
    if (year_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, year_);
    }
    if (!getDersNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dersName_);
    }
    if (ogrId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, ogrId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bilgeadam.grpc.OgrenciDers)) {
      return super.equals(obj);
    }
    com.bilgeadam.grpc.OgrenciDers other = (com.bilgeadam.grpc.OgrenciDers) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && (getOgrNumber()
        == other.getOgrNumber());
    result = result && (getYear()
        == other.getYear());
    result = result && getDersName()
        .equals(other.getDersName());
    result = result && (getOgrId()
        == other.getOgrId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + OGR_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOgrNumber());
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getYear());
    hash = (37 * hash) + DERS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDersName().hashCode();
    hash = (37 * hash) + OGR_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOgrId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.OgrenciDers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bilgeadam.grpc.OgrenciDers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OgrenciDers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OgrenciDers)
      com.bilgeadam.grpc.OgrenciDersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bilgeadam.grpc.OgrenciDers.class, com.bilgeadam.grpc.OgrenciDers.Builder.class);
    }

    // Construct using com.bilgeadam.grpc.OgrenciDers.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      ogrNumber_ = 0L;

      year_ = 0L;

      dersName_ = "";

      ogrId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_OgrenciDers_descriptor;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.OgrenciDers getDefaultInstanceForType() {
      return com.bilgeadam.grpc.OgrenciDers.getDefaultInstance();
    }

    @java.lang.Override
    public com.bilgeadam.grpc.OgrenciDers build() {
      com.bilgeadam.grpc.OgrenciDers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.OgrenciDers buildPartial() {
      com.bilgeadam.grpc.OgrenciDers result = new com.bilgeadam.grpc.OgrenciDers(this);
      result.id_ = id_;
      result.name_ = name_;
      result.ogrNumber_ = ogrNumber_;
      result.year_ = year_;
      result.dersName_ = dersName_;
      result.ogrId_ = ogrId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bilgeadam.grpc.OgrenciDers) {
        return mergeFrom((com.bilgeadam.grpc.OgrenciDers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bilgeadam.grpc.OgrenciDers other) {
      if (other == com.bilgeadam.grpc.OgrenciDers.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getOgrNumber() != 0L) {
        setOgrNumber(other.getOgrNumber());
      }
      if (other.getYear() != 0L) {
        setYear(other.getYear());
      }
      if (!other.getDersName().isEmpty()) {
        dersName_ = other.dersName_;
        onChanged();
      }
      if (other.getOgrId() != 0L) {
        setOgrId(other.getOgrId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bilgeadam.grpc.OgrenciDers parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bilgeadam.grpc.OgrenciDers) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long ogrNumber_ ;
    /**
     * <code>int64 ogr_number = 3;</code>
     */
    public long getOgrNumber() {
      return ogrNumber_;
    }
    /**
     * <code>int64 ogr_number = 3;</code>
     */
    public Builder setOgrNumber(long value) {
      
      ogrNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ogr_number = 3;</code>
     */
    public Builder clearOgrNumber() {
      
      ogrNumber_ = 0L;
      onChanged();
      return this;
    }

    private long year_ ;
    /**
     * <code>int64 year = 4;</code>
     */
    public long getYear() {
      return year_;
    }
    /**
     * <code>int64 year = 4;</code>
     */
    public Builder setYear(long value) {
      
      year_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 year = 4;</code>
     */
    public Builder clearYear() {
      
      year_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object dersName_ = "";
    /**
     * <code>string ders_name = 5;</code>
     */
    public java.lang.String getDersName() {
      java.lang.Object ref = dersName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dersName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ders_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDersNameBytes() {
      java.lang.Object ref = dersName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dersName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ders_name = 5;</code>
     */
    public Builder setDersName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dersName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ders_name = 5;</code>
     */
    public Builder clearDersName() {
      
      dersName_ = getDefaultInstance().getDersName();
      onChanged();
      return this;
    }
    /**
     * <code>string ders_name = 5;</code>
     */
    public Builder setDersNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dersName_ = value;
      onChanged();
      return this;
    }

    private long ogrId_ ;
    /**
     * <code>int64 ogr_id = 6;</code>
     */
    public long getOgrId() {
      return ogrId_;
    }
    /**
     * <code>int64 ogr_id = 6;</code>
     */
    public Builder setOgrId(long value) {
      
      ogrId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ogr_id = 6;</code>
     */
    public Builder clearOgrId() {
      
      ogrId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OgrenciDers)
  }

  // @@protoc_insertion_point(class_scope:OgrenciDers)
  private static final com.bilgeadam.grpc.OgrenciDers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bilgeadam.grpc.OgrenciDers();
  }

  public static com.bilgeadam.grpc.OgrenciDers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OgrenciDers>
      PARSER = new com.google.protobuf.AbstractParser<OgrenciDers>() {
    @java.lang.Override
    public OgrenciDers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OgrenciDers(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OgrenciDers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OgrenciDers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bilgeadam.grpc.OgrenciDers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

