// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isUpdated = 1;</code>
   */
  boolean getIsUpdated();
}
