// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

public interface OgrenciListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OgrenciListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Ogrenci ogrenci = 1;</code>
   */
  java.util.List<com.bilgeadam.grpc.Ogrenci> 
      getOgrenciList();
  /**
   * <code>repeated .Ogrenci ogrenci = 1;</code>
   */
  com.bilgeadam.grpc.Ogrenci getOgrenci(int index);
  /**
   * <code>repeated .Ogrenci ogrenci = 1;</code>
   */
  int getOgrenciCount();
  /**
   * <code>repeated .Ogrenci ogrenci = 1;</code>
   */
  java.util.List<? extends com.bilgeadam.grpc.OgrenciOrBuilder> 
      getOgrenciOrBuilderList();
  /**
   * <code>repeated .Ogrenci ogrenci = 1;</code>
   */
  com.bilgeadam.grpc.OgrenciOrBuilder getOgrenciOrBuilder(
      int index);
}
