// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OgrenciDers.proto

package com.bilgeadam.grpc;

/**
 * Protobuf type {@code Ogrenci}
 */
public  final class Ogrenci extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ogrenci)
    OgrenciOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ogrenci.newBuilder() to construct.
  private Ogrenci(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ogrenci() {
    id_ = 0L;
    name_ = "";
    ogrNumber_ = 0L;
    year_ = 0L;
    ders1_ = "";
    ders2_ = "";
    ders3_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Ogrenci(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            ogrNumber_ = input.readInt64();
            break;
          }
          case 32: {

            year_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            ders1_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            ders2_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            ders3_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_Ogrenci_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_Ogrenci_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bilgeadam.grpc.Ogrenci.class, com.bilgeadam.grpc.Ogrenci.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OGR_NUMBER_FIELD_NUMBER = 3;
  private long ogrNumber_;
  /**
   * <code>int64 ogr_number = 3;</code>
   */
  public long getOgrNumber() {
    return ogrNumber_;
  }

  public static final int YEAR_FIELD_NUMBER = 4;
  private long year_;
  /**
   * <code>int64 year = 4;</code>
   */
  public long getYear() {
    return year_;
  }

  public static final int DERS1_FIELD_NUMBER = 5;
  private volatile java.lang.Object ders1_;
  /**
   * <code>string ders1 = 5;</code>
   */
  public java.lang.String getDers1() {
    java.lang.Object ref = ders1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ders1_ = s;
      return s;
    }
  }
  /**
   * <code>string ders1 = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDers1Bytes() {
    java.lang.Object ref = ders1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ders1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DERS2_FIELD_NUMBER = 6;
  private volatile java.lang.Object ders2_;
  /**
   * <code>string ders2 = 6;</code>
   */
  public java.lang.String getDers2() {
    java.lang.Object ref = ders2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ders2_ = s;
      return s;
    }
  }
  /**
   * <code>string ders2 = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDers2Bytes() {
    java.lang.Object ref = ders2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ders2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DERS3_FIELD_NUMBER = 7;
  private volatile java.lang.Object ders3_;
  /**
   * <code>string ders3 = 7;</code>
   */
  public java.lang.String getDers3() {
    java.lang.Object ref = ders3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ders3_ = s;
      return s;
    }
  }
  /**
   * <code>string ders3 = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDers3Bytes() {
    java.lang.Object ref = ders3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ders3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (ogrNumber_ != 0L) {
      output.writeInt64(3, ogrNumber_);
    }
    if (year_ != 0L) {
      output.writeInt64(4, year_);
    }
    if (!getDers1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ders1_);
    }
    if (!getDers2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ders2_);
    }
    if (!getDers3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ders3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (ogrNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, ogrNumber_);
    }
    if (year_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, year_);
    }
    if (!getDers1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ders1_);
    }
    if (!getDers2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ders2_);
    }
    if (!getDers3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ders3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bilgeadam.grpc.Ogrenci)) {
      return super.equals(obj);
    }
    com.bilgeadam.grpc.Ogrenci other = (com.bilgeadam.grpc.Ogrenci) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && (getOgrNumber()
        == other.getOgrNumber());
    result = result && (getYear()
        == other.getYear());
    result = result && getDers1()
        .equals(other.getDers1());
    result = result && getDers2()
        .equals(other.getDers2());
    result = result && getDers3()
        .equals(other.getDers3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + OGR_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOgrNumber());
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getYear());
    hash = (37 * hash) + DERS1_FIELD_NUMBER;
    hash = (53 * hash) + getDers1().hashCode();
    hash = (37 * hash) + DERS2_FIELD_NUMBER;
    hash = (53 * hash) + getDers2().hashCode();
    hash = (37 * hash) + DERS3_FIELD_NUMBER;
    hash = (53 * hash) + getDers3().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.Ogrenci parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.Ogrenci parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bilgeadam.grpc.Ogrenci parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bilgeadam.grpc.Ogrenci prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ogrenci}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ogrenci)
      com.bilgeadam.grpc.OgrenciOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_Ogrenci_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_Ogrenci_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bilgeadam.grpc.Ogrenci.class, com.bilgeadam.grpc.Ogrenci.Builder.class);
    }

    // Construct using com.bilgeadam.grpc.Ogrenci.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      ogrNumber_ = 0L;

      year_ = 0L;

      ders1_ = "";

      ders2_ = "";

      ders3_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bilgeadam.grpc.OgrenciDersOuterClass.internal_static_Ogrenci_descriptor;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.Ogrenci getDefaultInstanceForType() {
      return com.bilgeadam.grpc.Ogrenci.getDefaultInstance();
    }

    @java.lang.Override
    public com.bilgeadam.grpc.Ogrenci build() {
      com.bilgeadam.grpc.Ogrenci result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bilgeadam.grpc.Ogrenci buildPartial() {
      com.bilgeadam.grpc.Ogrenci result = new com.bilgeadam.grpc.Ogrenci(this);
      result.id_ = id_;
      result.name_ = name_;
      result.ogrNumber_ = ogrNumber_;
      result.year_ = year_;
      result.ders1_ = ders1_;
      result.ders2_ = ders2_;
      result.ders3_ = ders3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bilgeadam.grpc.Ogrenci) {
        return mergeFrom((com.bilgeadam.grpc.Ogrenci)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bilgeadam.grpc.Ogrenci other) {
      if (other == com.bilgeadam.grpc.Ogrenci.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getOgrNumber() != 0L) {
        setOgrNumber(other.getOgrNumber());
      }
      if (other.getYear() != 0L) {
        setYear(other.getYear());
      }
      if (!other.getDers1().isEmpty()) {
        ders1_ = other.ders1_;
        onChanged();
      }
      if (!other.getDers2().isEmpty()) {
        ders2_ = other.ders2_;
        onChanged();
      }
      if (!other.getDers3().isEmpty()) {
        ders3_ = other.ders3_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bilgeadam.grpc.Ogrenci parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bilgeadam.grpc.Ogrenci) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long ogrNumber_ ;
    /**
     * <code>int64 ogr_number = 3;</code>
     */
    public long getOgrNumber() {
      return ogrNumber_;
    }
    /**
     * <code>int64 ogr_number = 3;</code>
     */
    public Builder setOgrNumber(long value) {
      
      ogrNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ogr_number = 3;</code>
     */
    public Builder clearOgrNumber() {
      
      ogrNumber_ = 0L;
      onChanged();
      return this;
    }

    private long year_ ;
    /**
     * <code>int64 year = 4;</code>
     */
    public long getYear() {
      return year_;
    }
    /**
     * <code>int64 year = 4;</code>
     */
    public Builder setYear(long value) {
      
      year_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 year = 4;</code>
     */
    public Builder clearYear() {
      
      year_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object ders1_ = "";
    /**
     * <code>string ders1 = 5;</code>
     */
    public java.lang.String getDers1() {
      java.lang.Object ref = ders1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ders1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ders1 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDers1Bytes() {
      java.lang.Object ref = ders1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ders1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ders1 = 5;</code>
     */
    public Builder setDers1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ders1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ders1 = 5;</code>
     */
    public Builder clearDers1() {
      
      ders1_ = getDefaultInstance().getDers1();
      onChanged();
      return this;
    }
    /**
     * <code>string ders1 = 5;</code>
     */
    public Builder setDers1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ders1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ders2_ = "";
    /**
     * <code>string ders2 = 6;</code>
     */
    public java.lang.String getDers2() {
      java.lang.Object ref = ders2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ders2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ders2 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDers2Bytes() {
      java.lang.Object ref = ders2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ders2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ders2 = 6;</code>
     */
    public Builder setDers2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ders2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ders2 = 6;</code>
     */
    public Builder clearDers2() {
      
      ders2_ = getDefaultInstance().getDers2();
      onChanged();
      return this;
    }
    /**
     * <code>string ders2 = 6;</code>
     */
    public Builder setDers2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ders2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ders3_ = "";
    /**
     * <code>string ders3 = 7;</code>
     */
    public java.lang.String getDers3() {
      java.lang.Object ref = ders3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ders3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ders3 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDers3Bytes() {
      java.lang.Object ref = ders3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ders3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ders3 = 7;</code>
     */
    public Builder setDers3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ders3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ders3 = 7;</code>
     */
    public Builder clearDers3() {
      
      ders3_ = getDefaultInstance().getDers3();
      onChanged();
      return this;
    }
    /**
     * <code>string ders3 = 7;</code>
     */
    public Builder setDers3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ders3_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ogrenci)
  }

  // @@protoc_insertion_point(class_scope:Ogrenci)
  private static final com.bilgeadam.grpc.Ogrenci DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bilgeadam.grpc.Ogrenci();
  }

  public static com.bilgeadam.grpc.Ogrenci getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ogrenci>
      PARSER = new com.google.protobuf.AbstractParser<Ogrenci>() {
    @java.lang.Override
    public Ogrenci parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Ogrenci(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Ogrenci> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ogrenci> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bilgeadam.grpc.Ogrenci getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

